language: node_js
node_js: 6
sudo: required
git:
  depth: 5
branches:
  only:
  - "/^(?i:SWIK)-.*$/"
  - master
cache:
  directories:
  - "./application/node_modules"
before_install:
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./travis_scripts/install_compose.sh ; fi
- cd application
script:
- sleep 15
- npm run lint
after_success:
- cd ..
- openssl aes-256-cbc -K $encrypted_cd8e0a18433b_key -iv $encrypted_cd8e0a18433b_iv -in deployment_keys.tar.enc -out deployment_keys.tar -d
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./travis_scripts/dockerhub.sh ; fi
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./travis_scripts/deploy.sh ; fi
- cd application
after_script:
- npm run coverall
- rm -f deployment_keys.tar
- rm -f ~/.docker/{cert.pem,key.pem,ca.pem,config.json}
services:
- docker
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: Vq7NZX+k54ex102D4IYaqKX3pC3m+PX1o3iYeMH4lMohYUgGWhRvLICgmWr8v4mDVviFbPKSR1CRQnboWIqA2wrCMnH+2p6bexQxiAuwxywfNHl1lT9bFuk+nCEM2I/rtzZ55tAFAVPOnjWjcyUGHr+0u3iLUfwu6RxCkoIgU8hMmlEagkokvWgSTDsLPGnvbsQSXXcKagjxyNmBmBgK7Qec9ubGlYL5XKZLzX4WBbGeciBg8GjYLQP/xMJbeTOGMbN0MOBaO43577SENitJuylsZM0nzlAvTX6dUfTuaMh81KETAR+I0jYKg9AM4T+9H+oTkB24iQmKm4iOp3f4W8hH7Hr38uFoYkPgvD7a4iSRceu2ytKJwC11OON8ZhqNrBYAjF1mkhrGtGZNlGaU94RN8PyPUZp6XQhF7Kmyxrbv8dQ4nAvCHxYw+HS7+aWur6w1Y9WsU1N2FU/tjnAqRlO2i9jwkf3Vb5fgG2yHB1aLPOzHNMO9Pek1CYPJlFREy6tn+TGQuQ7aExu1JhC/5DzNkKxBNgbyVXsd1+vfbVfnMAqVzLDHdHT91q5XVatpCbNErfdmGvJt8LbocdZupzQDFYbEev2RWT3LiNz2mrOuhURyBlcru9+x4pjIbcXFfyqQKrEQaRiRkIBWpTFGC2UOkarVLxh67M6LRB+uvHk=
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.6.2
  - DATABASE_PORT=27018
  - secure: UsIcQLR2JH13FDWTo45cj8Fdnu159UhXIpoG0WVUdsXiFpGMYfXaILPppah6u59HdGpcii4fDoT2JeJzLH4DNNmfIJg8KFWxzpHra2dziA7b065OkH10xyJKqzuKmS2wVkkeAPJc3IE5LNbbspJzFr5aPLK31HREg1xyRRsncRoVBka4PFkAuRw/hHeoVmq+ymDFNfemneJIvPINJku3mrglgrnS9yoHT0eR+yJ7CmZ04YSF6ZbqWkUttyIngXCDW2rP8ngLSXtWsBpiJmc7Fp28enXozL5lU52AuZJhJJy3N4uY884dj0X2gBMz1PVzHYjvlnMKE1c8vyarKgpb01lY7EqqSQWQlOWMBKxrWk1xqeWwqF3uooJ1u+ZZ4iaFHHBd9LbGd7rNlbpFSsM2Rwl3NvpVjz0hCj8pbM4P+l14R3UDX0lsWVVNJxKCjdxROejlteKuPoAZDF3H2PgOeOOnSt02ykstdDW6+7qvehVnNaqobof6QBaVYC02hJPx+s5uVUKY/qRSsNdpsA3tvlz68IwGs1ksFOcklvJJGZeGXGwzzokPicNHwuoWkdV2Q5saYWHFCE7yW4pG5SU3lgvKcipk5O57V9cN9uS4fB5PwVYg0bZwYMDDLoZJ6+NRN14fEC5FPjXLyHGD7NtQQwYCdevgXNY0dP1nkUMFSK0=
  - secure: GHTZs9yM5smtO5DjcBNi5duz30Al6dvHg4PkMFAxCNghEJ4CMdFfOYrbwPPcVFU25IUsB64GiA/lVmRweguGZlzOGFdoefl8/M24vjw7DVgF5+2yXWp0KNsMfhAEfKmZTd35N1hgVJnICWfUK5cGW50iPYgl+VsD2VYqx4QtDP6B1LF9WzXgqMyaP3MSVFhcI2A1QOj90Bjv+wc5s53jPIGoSygvyf8eurhtaSaDpJRdoi/bSrzYf6op/I5+eo6Q30IQzx38ZJD3kP7Gp2Ueq8rq9vqS3HCupeAS6loYvcYfwCJKDRuOQ5dKZ02bCJSfppt2/JH9BIYMGxH9lotElNDKAaNqRYNmuCKaW4QdbfY9IjoxgJ/Gtn+qedVdghkakAuSDq23pql/9z52s5gfuUXLcvS6GUwxFn87KnVzL+32Os6YvrPrvgt9y4X0DDQM9hTGJcTIR+hIqSpklMRGDMON+n5k3mNartAKGse3GnSfe6KP9d7ua+38bEncRdFWtUnRNcfP247T0eQl1J/VpZZjkQtEDVNECo03evlLQBYqkAkXdreFkGKGQloBwJLHyY9aBBIbsczxCvkfU9dZALPOtudptdnjCaUcK+tc6Ll3fJhqlsw2ictpilniB1WkNLpS/EtnCnLQMJzKkUxq1vC07HbiMv0zRgsCmw+XkbE=
  - secure: B8h546EQHeacCfk8NTtCODFTf9669SiVFK0iJNVVlNoBJ+pnVnus0uef7wGYSQl8WsTV7246L20izm/ki9zO8mnDV0wv7+/S6/dsfFIeQKndAVxdgI7m68Y9a55gyUYyKFT/GRb8nuEYX60MYP/RfPr2etn8diw0c6zHn8R0GLCNbQ9pXiokYlWrXm04JWxvGfc8j6vcAJQgwP28WPBopNyJu2BR8UFVWQSa1OhGwMFxvwJ/PMs0etr2BblGMA7aB35QDfsUQUmIfgvd8qS/iRe5yMbjEDqxNEmu4iaSid4XzTB82zKfXApzH948c//KUMeQFv2iQMTrF7zxciPUdnySGuhhUjyUb5oTiEONAwegMqatNKWUuoSjzSni9cmRdX5aWyEPiDQ30/R8g1bOANiyi8fXhmRYzWOSXGpPzYvuyGKQEqHFaIYPRBi5zsPxASfI4HYS1yh1aszqkMvi54ws2lWc1nrZqljimSuxHo1zAsJ/iviKByrmAHF4L4+4g5HdB+pjd1pZSpPsl6Cb6YWTk5EngoNB8fhQ8f9p/rsVMqzcrhkURYBIgYRLpwcLoNdNRUKVAVoqTbAqrhnDAQN/xtEKGynjbQfpwTvVwms0F1SwbCB3UXGbpZBmRviwW/LG7JrLTlVz3qh8D4Y+lLCUUrMh4U+pPL05WdMrSyc=
  - secure: l4roX76lmVJIeySyHfq+Zd5VY7wyP8TkO2KdlPYlCFGM9WfsRHJDNIjsbTz2ZOGxp1XJcXiCl1rDYm/uZTQLMYMCy5Vk6TfIyIo6ckmKqkFEYOmmla9NS9kJVjStAy5ZPJuPkGnWvggiiRsXL01jUZrwsNea89uDgEVKA56c48DoEhm203ecvHQ8BSycOiN8H1QB4MbLs67ie5i1CIIhhdcIPQpQjeQnwTdKT2iVFGpK2Tk77IqiQUnl4aUq4lHvHj478BmZ4VUzDnk365vRbqRRp0NoK9EhU3QvvqciA+crSMF809IHsL6ORqNhlGxJFmudyeRHAkM6kG9qip49uynZkDwGem80dwyDaD4zyY78swrR1YOF72koI8KvULG0DVLzj7pZY2u9nBbjB3HTB/+27BGv+8DKazlywCNhxz2MXlOZJtwbeVG366kT+HInw4q7Au+8CAcrurivK4dBEqxUTIWWDF2dfw/rds2jxLawjkX6wa497cyeUPmb6VMoJCZMZ9O/xrF+5XZAA17QmR0PZ2iIrlQnuYpgMX9x8FU5IWCO9HloHEIPiOIVrHuYX1Canr6PRCEL5Su7dGnEOUCW3zjkZaOxuUj3bA+Owv+6p4DTyg5LiL9wItjvHdAV0b7ZOZ+tapdxQHIsjA3Yu4luLWLLuYEXs/L0ahC1HCg=
