language: node_js
node_js: 6
sudo: required
git:
  depth: 5
branches:
  only:
  - "/^(?i:SWIK)-.*$/"
  - master
cache:
  directories:
  - "./application/node_modules"
before_install:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/install_compose.sh ; fi
- cd application
script:
- npm run lint
after_success:
- cd ..
- openssl aes-256-cbc -K $encrypted_eeb84546b5d6_key -iv $encrypted_eeb84546b5d6_iv -in deployment_keys.tar.enc -out deployment_keys.tar -d
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/dockerhub.sh ; fi
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] ; then ./travis_scripts/deploy.sh ; fi
- cd application
after_script:
- npm run coverall
- rm -f deployment_keys.tar
- rm -f ~/.docker/{cert.pem,key.pem,ca.pem,config.json}
services:
- docker
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: Vq7NZX+k54ex102D4IYaqKX3pC3m+PX1o3iYeMH4lMohYUgGWhRvLICgmWr8v4mDVviFbPKSR1CRQnboWIqA2wrCMnH+2p6bexQxiAuwxywfNHl1lT9bFuk+nCEM2I/rtzZ55tAFAVPOnjWjcyUGHr+0u3iLUfwu6RxCkoIgU8hMmlEagkokvWgSTDsLPGnvbsQSXXcKagjxyNmBmBgK7Qec9ubGlYL5XKZLzX4WBbGeciBg8GjYLQP/xMJbeTOGMbN0MOBaO43577SENitJuylsZM0nzlAvTX6dUfTuaMh81KETAR+I0jYKg9AM4T+9H+oTkB24iQmKm4iOp3f4W8hH7Hr38uFoYkPgvD7a4iSRceu2ytKJwC11OON8ZhqNrBYAjF1mkhrGtGZNlGaU94RN8PyPUZp6XQhF7Kmyxrbv8dQ4nAvCHxYw+HS7+aWur6w1Y9WsU1N2FU/tjnAqRlO2i9jwkf3Vb5fgG2yHB1aLPOzHNMO9Pek1CYPJlFREy6tn+TGQuQ7aExu1JhC/5DzNkKxBNgbyVXsd1+vfbVfnMAqVzLDHdHT91q5XVatpCbNErfdmGvJt8LbocdZupzQDFYbEev2RWT3LiNz2mrOuhURyBlcru9+x4pjIbcXFfyqQKrEQaRiRkIBWpTFGC2UOkarVLxh67M6LRB+uvHk=
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.8.0
  - DATABASE_PORT=27018
  - secure: eaZiG10eXup7EjUqm7B2vrsmNxZwLESidEUMPszb8Rtcq2aVeUBZnAsxEiKwZXd20tqRpel92XPw7VrpUXhNcIA7PABA5DT5fRz25yW6+dAZOMhwUecebemC8gS73ljG6T7pkJPwCaFThCHEpgP3IOEQAKET06dCFrA1jF+0zetNl6/z8gNEUCwqpbo24/gF4WONb+5gEDaxWyJkfFqIX4JSfHn2sAA5LLkw8T7YRmXnctpoAcW7QQ8qJfTJoJPhwj0rcofCk5PpgN5hYf7QKWbSf1KeLC6lJLLQR5TH06N4bLxR9RGZOEll9m2JEbzN+WWeA5nfn01WvB5ebxNdqUqlqj8yp9z7FbTcQb1U9qlNxZaItiianfIgQNsNxijuDsbOQRykD+dsRfRwasRfa8SwXh35geRresYtj/tOW7tKILUW3fT6Ct7kaOs2dXZhKJzVzPergl/Th5Xyofn5+G0PJ5zkdiAKVEzlQOOwJeWLSgS2u55k3by/IInfCosBHENPm61JvSsKEwLnQiqHfOLXYUpwaCRtnCRebju+0hezeEhXAr17bZ1+nKw7AmzfM+TJziVxpWFaUFcGdMuJQmqY2IEBuSK9mP3sC+LnTscKvELV0gCQ7dcT32CgUxWtCi5hpB+MJrTt2aBnpce6ODpO6L+lg7HD9yGG0PegCHM=
  - secure: m4+M9Jx4wWxJiYboEzs024vLRo285kM96+C4lroO4ZB1kZhPNQHPuM5Sjlqt0M8zmqS8gceiWUEhguv0yZ8xJKcT0KRGrIeBYnUCdNFxk5vNId3EYUrq8c4We1CdyiptZo4ro885aEtiIHicshoJumrHqEMC9XPeV4LIXCJvWGGYmX5Ti/Ga1Q38STuKgfWjQOCiwsEmO/IdVL285nYbDvVCJnngeB/dFdy/jtCDaAk1fFcTqXFvFQDytcmid3iXBPXiFnkthuz1aFnRFpI2OU5QG13mcwHop7lHTxi45hLdnU0gmUUh9oXVLck57bszM5t8HDnk1zxOjP7MAs4V3JhlgiLqHJ3AqjbuKvl84PSrfqUnnYNZyeK6ho3Mf57Dg39oFuA+1dlxEAqM1M0v/SfslcaMdiYkF/+VqoYh3kc/NeT25GgmnTSYo/RZvOC6eNCukEWhQiJril0g9jkrl9KkyN4OfeG3X1/Q+AfdMj+o+ZocVe9fHVcNjuexBdHpcSqwQYtufqq9weMDGNzJKTz+P+okxtlSwFFFKo58t1zkKx9WD/5RcqQ1nTxw0iKNT3V81VU030Jle5wd+Vzov8c+yCiudy2J0vxr7wqg6fk7Dt2YjKJN4z8Kn0YVJnqpZACuWxyQ0KP2klPM3lEYNQaixtp8+2fZlGTGWnwvZaA=
  - secure: KnKiFvyfKUwLfXHMQHFyroRKW6bw3rZx439bBWL3Dq5eaRSO9en1HivcDlvCXxNnCqlDiPcNtyWWLq7w9c1AClI4u/3EG7mNV/cy7JXZbtx4bvCSWETz5ByT/qI3ZL0On+zwxQJi0ghvHxQlV1L/ZDdhCAVC5R1tQeWQj/LldgnRgiNx1yJy8josA2zpTLwoBg5qTF2vGpJ6on/vAveglvupJM1vDDln7LZyMtjrdlXenjX/93btO8enPeaSKHCdUL6EzAe0hXYXqGVjmf7gwVEKjIOTNkCQcG9x99dxQp2ZhNvCRfF5DrnKg48Yt+izC9nLctmLpihsrFlJI8NiHRXg4Fv2gdZruV4PiNx0euH1Y4cw43mbcVcBa0vlLG6ZIuxuJWSOI/xbT90CDx3QxkoZubyBDz+d6uYjhJ7Boe+hkMTmi0z69fbNzvOUnRy3bMiGL4nnZmfuA3PPL5mXssvJShJM1/c4UOrqwIl2jflgqYCHwZGzkkMTN9w6RKpK+EJ0lsMhCtC/7qYxCx96quoXakNeYYqzhfAbM5IcIOqgSc0ENm7xWI3sa/NSCw0uFryNR2c4FO6RtAqT3eBrjK5u0z+VIvvWYOzBLQuaYsoUl6torVpc/nNsXI1SfuKjkuFQIRMBL6zThWvy2H3j2GivwhPjWnc2MQ9bGCNGsOQ=
