language: node_js
node_js: 6
sudo: required
git:
  depth: 5
branches:
  only:
  - "/^(?i:SWIK)-.*$/"
  - master
cache:
  directories:
  - "./application/node_modules"
before_install:
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./travis_scripts/install_compose.sh ;
  fi
- cd application
script:
- sleep 15
- npm run lint
after_success:
- cd ..
- openssl aes-256-cbc -K $encrypted_cd8e0a18433b_key -iv $encrypted_cd8e0a18433b_iv
  -in deployment_keys.tar.enc -out deployment_keys.tar -d
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./travis_scripts/dockerhub.sh ; fi
- if [ "$TRAVIS_BRANCH" == "master" ] ; then ./travis_scripts/deploy.sh ; fi
- cd application
after_script:
- npm run coverall
- rm -f deployment_keys.tar
- rm -f ~/.docker/{cert.pem,key.pem,ca.pem,config.json}
services:
- docker
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: Vq7NZX+k54ex102D4IYaqKX3pC3m+PX1o3iYeMH4lMohYUgGWhRvLICgmWr8v4mDVviFbPKSR1CRQnboWIqA2wrCMnH+2p6bexQxiAuwxywfNHl1lT9bFuk+nCEM2I/rtzZ55tAFAVPOnjWjcyUGHr+0u3iLUfwu6RxCkoIgU8hMmlEagkokvWgSTDsLPGnvbsQSXXcKagjxyNmBmBgK7Qec9ubGlYL5XKZLzX4WBbGeciBg8GjYLQP/xMJbeTOGMbN0MOBaO43577SENitJuylsZM0nzlAvTX6dUfTuaMh81KETAR+I0jYKg9AM4T+9H+oTkB24iQmKm4iOp3f4W8hH7Hr38uFoYkPgvD7a4iSRceu2ytKJwC11OON8ZhqNrBYAjF1mkhrGtGZNlGaU94RN8PyPUZp6XQhF7Kmyxrbv8dQ4nAvCHxYw+HS7+aWur6w1Y9WsU1N2FU/tjnAqRlO2i9jwkf3Vb5fgG2yHB1aLPOzHNMO9Pek1CYPJlFREy6tn+TGQuQ7aExu1JhC/5DzNkKxBNgbyVXsd1+vfbVfnMAqVzLDHdHT91q5XVatpCbNErfdmGvJt8LbocdZupzQDFYbEev2RWT3LiNz2mrOuhURyBlcru9+x4pjIbcXFfyqQKrEQaRiRkIBWpTFGC2UOkarVLxh67M6LRB+uvHk=
env:
  global:
  - DOCKER_COMPOSE_VERSION=1.6.2
  - DATABASE_PORT=27018
  - secure: ecBx8vhj3iN/7Ev+64walxU1f14fdVkpWw4IoIFCW3VSQ9ZPv36EhE+9F+T7b6+7VE7doRhncupO5VriOxeF25fa9fXykT/4e7uiLpcGm26CnzEfhuPqsJunodjkpnxrK1451yJ35PDqmlhXDQD5Dr+C7tUur0yGm1Hf4LOCMW1tvUHi4Y5g4+ynY+yWiewRyrFWohLcM4bLk07QfnSX0FfK3ElkxvkUvxjNR5TULhTSoZ5xs/CFcF7npInOQQCYvH7tInKuLMWuuIPwVdbNGY0hGjW85sD9PMtRhi94CA1Mop5un2FOX6C9p+RM+EnGHhW41fqAkCGso4RFk31XIIwUBAgkY94pXOK5PMA34khEzz10dzK/xy+jSWlTGSCKd4NSz/8Fj0oVmbmFixXIfoGwG++X1wdn6RA1MfDcJDJ++XFKp9N0HQvhazypSSOKiTiwgn44P+NWOpExuVw1KFo9YEqhZFgyM8yP+T2+93canK5T3uJRMr8Jawq2sVSCzVAGt3CgoU+5vlcVEqiPkNKgOF8ngbwUhCfqOY0HMfrTmsuk4m2NDD3LGWzHkyIDpS2XMTukF6T1C3mrPsMxIR65QlMzPSAubID4mcUAYjOWE4kHWeoja2GHwieyKv3XwqMUvduj3c+27v24dDakgRlVGVbFWV1/19RUpFb7z6Q=
  - secure: n3XunsJ6w85aDuxmb5fRJVpQ4NgoRCU8dIJfKfFliF24KjBR8YO9V/WCCBYx8PiVK/a9ce+5tTu6A+kbqA70MLw9eJGpLLb3RihDcTDWohxepo5kb2YB26UiK+RhM/xzZSuC4wql7tTmsTXi9nu8wlxRT2kYALmlV3g/o5fzFz9xSS5wHpCDEi/OI5JGFqDF5s9Khj9gISn8dkIV9QKTk0w+IDppqvgKNUN2ALBj59y5gL/ZVqwLiWlH5ickk1oK6JJ7oKVwHCgP3ACullMQkvCKHgPegeqE5ENYW4Rmn9KLnlZF64u/PzS0BUhZ4/VeXZYJebgnltrCPvRbzbzEpBS1eyMbXKjHu8fNFElCk+VPmeN96tbJoqC7o6w2XUL0BQY2KuoBN/xiHRdf7ZhO4iqL5lGtG6mrQ/yVpj35k7Fhs6BmpjagqqfybZ2NAaLkPlreD//Rry6v10iZu973jEuPZn6H2rmo9xo15ju6xc5d7BTjXQiYOWTKPBPmoDXQ4iib8gAjXE7cxGPmYOW2JRjciZsYB9sEWoOPsTJyexvdhw0VyisU1Zz6Ueqnyn+hnEmiusj7q/jEd+bJtxuQSFFVDmV/WURjDSdHjMMfo7LD5NkUTKQUXM1aD0hVYWzEYS304kOjGxfg0d5Y1ns1mmkna2AvrRXDboe6zQWJxKE=
  - secure: tv4A0QqGHU9xEhn5G4I1HuZk8qzZKtkJ1kXcKf6FUig0cqKvnZZKlUgPjaZyg72osae5os+wrntKzYIOWhuptx/HbiaGS0LtFcBwphHOXS+2A9wTYATm9GqbQoXAZbedkQJJeNw9u9IThv+jigRtH8piuHAVTwE4l7GNp+14coLO3kpKYByoJL6SUMSe/mUkgE54/g4gskuh60q+nNOwdW9Qlg6rRxGuEM6Z4/SLEu3ZlLwmYV5WzXu+NXb3+p6HCK4KsWnWvDcZeooZgDXfK2GxAhyB0JgkKGccqTWtxRiX7G/KpGaCTrYeqBmv/0CNKo06FgxkJyrIHfyMgy0luZTXc+792N3SFLTbpfQONNe7wOrF8KF7OaQqrEfS/5fydzS4irvfo7XD49NjaO7xWZ+5vHL9VXfjX/S0DJQ5B2oRJZjyDhAkNwgDbqJztDbSjYh9rW2EGEe4VRWaYJg9Ul9bf64ApIpD8LChylYVXafYmZy10ymp0XiaQg/8QlA6GcmDAW7rM/wl1qgUPuEYjLimBXO7H4Uh3eCOonRtBV6BMQ1KegrKUlQMkCILgXdOZ+QuSE1Or1Wy114QGv3OxzV5zHsMJv/L2Tr9qdtdYdfHKOsYHchVayiw6lCkHdNOyEevuoo0/lvF6mentJQJ9yOJkNCv9PsReb6xH0JwmZA=
  - secure: b6R4BcMDVYwsrsB+ZVlUAbme+Pkghtf24K6Jr/8c7qiL8CTj0jHim5dTb17mtEbDm1dDH59iEbDX2mluELJZ2AAAUl+raMLDeuyU38aiQ45zTUf6l34+FpdJBRlF40LgsnOcl9FJyBceWk/IIpd//glEP4JkXYVVlMxvR4hmNzP73NsDxVlGU3k0QrenMZVHXyy/fJQPIxkxThEjfmGbm8pRRWy2cm8OiJMC0a90ukIcNwp3etoOIYqhT/fiUanIAzZMiAfiWht2MQknWAd18x+i6OvsMm0OVrLWHQ3U+51T5as94geIzUasL2YGO0JugLSXLSOHzS9DI6qzvZowDCA+mb+ky8aj6AEn6xHV4clUxu1/SxHRZxdKNOPA4MkVAIMtrv1pz7+4vZ6ChvA5ME8sDYIiXs2RFA3Zaci/J+dmJjnUY5PvTnBPCIuC+CHxXMCTLs0w4l+89Xo7QvGqyIKo5zNW9rdzTNr4wBlJFCgxF3r3nM2edfTqpdqVIStVOiZSHkmpx4yOjoXSsZLWmONazHJkkIVHKYapeIAIawpZ3SP4WAgz8LuSp1JViHrEkedGk+AdF5kCxhgTbIwu5OK7dVj45aMpHFI41qL3ifpueAgTfpGONgfzWUbFQdyWsk+ywx/SShZFHXDijG1LUb529Fnl5oNqzDvSeTojfYo=
