pdfservice:
  image: slidewiki/pdfservice
  restart: on-failure:5
  expose:
    - "80"
  environment:
    - APPLICATION_PORT=80
    - VIRTUAL_HOST=pdfservice.experimental.slidewiki.org
    - SERVICE_URL_PLATFORM=http://platform.experimental.slidewiki.org
    - SERVICE_URL_DECK=http://deckservice.experimental.slidewiki.org
    - SERVICE_URL_PDF=http://pdfservice.experimental.slidewiki.org
